[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ovos-tts-plugin-SAM"
dynamic = ["version"]
description = "SAM tts plugin for mycroft"
license = "Apache-2.0"
authors = [
    {name = "JarbasAi", email = "jarbasai@mailfence.com"}
]
keywords = ["mycroft", "OpenVoiceOS", "OVOS", "chatterbox", "plugin", "tts"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Text Processing :: Linguistic",
    "Programming Language :: Python :: 3"
]
dependencies = [
    "ovos-plugin-manager>=2.1.0,<2.2.0"
]

[project.urls]
Homepage = "https://github.com/OpenVoiceOS/ovos-tts-plugin-SAM"

[project.entry-points."opm.tts"]
"ovos-tts-plugin-SAM" = "ovos_tts_plugin_SAM:SAMTTS"

[project.entry-points."opm.tts.config"]
"ovos-tts-plugin-SAM.config" = "ovos_tts_plugin_SAM:SAMTTSPluginConfig"

[tool.setuptools.dynamic]
version = {attr = "ovos_tts_plugin_SAM.version.__version__"}

[tool.setuptools.packages.find]
where = ["."]
include = ["ovos_tts_plugin_SAM*"]
